apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "coredns.fullname" . }}
data:
  Corefile: |-
    .:53 {
      {{- range $key, $middleware := .Values.middleware }}
      {{- if $middleware.enabled }}
      {{- if eq "rewrite" $key }}
        {{- range $entry := $middleware.entries }}
        rewrite name {{ $entry.from }} {{ $entry.to }}
        {{- end }}
      {{- end }}
      {{- if eq "kubernetes" $key }}
        kubernetes {{ $middleware.clusterDomain }} {
        {{- if $middleware.endpoint }}
          endpoint {{ $middleware.endpoint }}
        {{- end }}
          fallthrough
        }
      {{- end }}
      {{- if eq "etcd" $key }}
        etcd {{ range $middleware.zones }}{{ . }} {{ end }}{
          {{ if $middleware.path }}path {{ $middleware.path }}{{ end }}
          endpoint {{ $middleware.endpoint }}
        }
      {{- end }}
      {{- if eq "loadbalance" $key }}
        loadbalance {{ default "round_robin" $middleware.policy }}
      {{- end }}
      {{- if eq "log" $key }}
        log
      {{- end }}
      {{- if eq "errors" $key }}
        errors
      {{- end }}
      {{- if eq "health" $key }}
        health
      {{- end }}
      {{- if eq "prometheus" $key }}
        prometheus 0.0.0.0:{{ $middleware.port }}
      {{- end }}
      {{- if eq "proxy" $key }}
        proxy . /etc/resolv.conf
      {{- end }}
      {{- if eq "cache" $key }}
        cache 30
      {{- end }}
      {{- end }}
      {{- end }}
    }
