rbacEnable: {{RBAC_ENABLE}}
config:
  global:
    slack_api_url: {{SLACK_API_URL}}
  route:
    receiver: default-receiver
    repeat_interval: 3h
    routes:
    - match:
        alertname: DeadMansSwitch
      repeat_interval: 5m
      receiver: deadmansswitch
  receivers:
  - name: deadmansswitch
  - name: default-receiver
    slack_configs:
    - channel: '#devops'
      send_resolved: true

