rbac:
  create: {{RBAC_ENABLE}}
controller:
  config:
    ssl-redirect: "{{TLS_ENABLE}}"
    hsts: "{{TLS_ENABLE}}"
    disable-ipv6: "true"
  stats:
    enabled: true
  hostNetwork: {{ISMINIKUBE}}
  service:
    type: ClusterIP
    # nodePorts:
    #   http: 32080
    #   https: 32443

  # resources:
  #    limits:
  #      cpu: 100m
  #      memory: 64Mi
  #    requests:
  #      cpu: 100m
  #      memory: 64Mi
