rbac:
  create: {{RBAC_ENABLE}}
controller:
  config:
    ssl-redirect: "{{TLS_ENABLE}}"
    hsts: "{{TLS_ENABLE || false}}"
    disable-ipv6: "true"
  stats:
    enabled: true
  hostNetwork: true
  resources:
     limits:
       cpu: 100m
       memory: 64Mi
     requests:
       cpu: 100m
       memory: 64Mi
