apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-frontend
spec:
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  resources:
    requests:
      memory: 400Mi
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-frontend
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30901
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: prometheus-frontend
