{{- if .Values.ingress.enabled -}}
{{- $releaseName := .Release.Name -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  {{- if or (and .Values.ingress.annotations ) (not .Values.ingress.tls) }}
  annotations:
    {{- if not .Values.ingress.tls }}
    ingress.kubernetes.io/ssl-redirect: 'false'
    {{- end }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  labels:
    app: {{ .Chart.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "grafana.server.fullname" . }}
spec:
  rules:
    - host: {{ .Values.ingress.fqdn }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ printf "%s-%s" $releaseName "grafana" | trunc 63 }}
              servicePort: 80
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
