rbacEnable: false
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
    ingress.kubernetes.io/rewrite-target: /
  fqdn: prometheus.test-gce.idiotz.nl
  tls:
  - secretName: prometheus-server-tls
    hosts:
    - prometheus.test-gce.idiotz.nl
resources:
  requests:
    memory: 400Mi
externalUrl: https://prometheus.test-gce.idiotz.nl
