{{- if .Values.localproxy.enabled }}
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "fullname" . }}-proxy
  labels:
    app: {{ .Chart.Name | quote }}-proxy
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  template:
    metadata:
      name: {{ template "fullname" . }}-proxy
      labels:
        name: {{ template "fullname" . }}-proxy
    spec:
      containers:
      - name: {{ template "fullname" . }}-proxy
        image: "{{ .Values.localproxy.image.repository }}:{{ .Values.localproxy.image.tag }}"
        imagePullPolicy: {{ .Values.localproxy.image.pullPolicy }}
        env:
        - name: REGISTRY_HOST
          value: {{ template "fullname" . }}
        - name: REGISTRY_PORT
          value: {{ .Values.service.http.externalPort | quote }}
        ports:
        - name: registry
          containerPort: {{ .Values.service.http.externalPort }}
          hostPort: {{ .Values.localproxy.port }}
{{- end }}
