apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ .Chart.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      annotations:
{{ toYaml .Values.annotations | indent 8 }}
      labels:
        app: {{ .Chart.Name | quote }}
        release: {{ .Release.Name }}
    spec:
{{- if .Values.hostAliases }}
      hostAliases:
{{ toYaml .Values.hostAliases | indent 8 }}
{{- end }}
{{- if .Values.hostNetwork }}
      hostNetwork: {{ .Values.hostNetwork }} # minikube hack because cni can't seem to handle hostport even now (19 nov 2017)
{{- end }}
      containers:
      - name: registry
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
        env:
        - name: REGISTRY_HTTP_ADDR
          value: ":{{ .Values.service.externalPort }}"
        - name: REGISTRY_LOG_LEVEL
          value: {{ .Values.logLevel | quote }}
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: "/var/lib/registry"
{{- if .Values.proxy.enabled }}
        - name: REGISTRY_STORAGE_DELETE_ENABLED
          value: "true"
        - name: REGISTRY_PROXY_REMOTEURL
          value: {{ .Values.proxy.url }}
  {{- if .Values.proxy.username }}
        - name: REGISTRY_PROXY_USERNAME
          value: {{ .Values.proxy.username }}
  {{- end -}}
  {{- if .Values.proxy.password }}
        - name: REGISTRY_PROXY_PASSWORD
          value: {{ .Values.proxy.password }}
  {{- end -}}
        {{ range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{ end }}
{{- end }}
        volumeMounts:
        - name: image-store
          mountPath: /var/lib/registry
          subPath: "{{ .Values.persistentVolume.subPath }}"
        ports:
        - containerPort: 5000
          name: registry
          protocol: TCP
      volumes:
      - name: image-store
      {{- if .Values.persistentVolume.enabled }}
        persistentVolumeClaim:
          claimName: {{ if .Values.persistentVolume.existingClaim }}{{ .Values.persistentVolume.existingClaim }}{{- else }}{{ template "fullname" . }}{{- end }}
      {{- else }}
        emptyDir: {}
      {{- end -}}
