apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ .Chart.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
spec:
  selector:
    app: {{ .Chart.Name | quote }}
    release: {{ .Release.Name }}
  ports:
  - name: registry
    port: {{ .Values.service.http.externalPort }}
    targetPort: {{ .Values.service.http.externalPort }}
