apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "prometheus"
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    prometheus: {{ .Values.global.prometheus }}
    release: {{ .Release.Name }}
  name: {{ template "fullname" . }}
data:
{{- $root := . }}
{{- range $key, $val := .Values.ruleFiles }}
  {{ $key }}: |-
{{ tpl $val $root | indent 4}}
{{- end }}
