{{- if .Values.tcp }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Chart.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.controller.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "fullname" . }}-tcp
data:
{{ toYaml .Values.tcp | indent 2 }}
{{- end }}
