{{- if .Values.server.setDatasource.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: {{ template "grafana.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.server.name }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "grafana.server.fullname" . }}-set-datasource
spec:
  activeDeadlineSeconds: {{ default 300 .Values.server.setDatasource.activeDeadlineSeconds }}
  template:
    metadata:
      labels:
        app: {{ template "grafana.fullname" . }}
        component: "{{ .Values.server.name }}"
        release: "{{ .Release.Name }}"
    spec:
      initContainers:
      - name: grafana-listener
        image: sequenceiq/alpine-dig
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nslookup {{ .Release.Name }}-grafana.default.svc.cluster.local; do echo waiting for {{ .Release.Name }}-grafana.default.svc.cluster.local; sleep 2; done;']
      containers:
      - name: {{ template "grafana.server.fullname" . }}-set-datasource
        image: "{{ .Values.server.setDatasource.image }}"
        env:
        - name: ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "grafana.server.fullname" . }}
              key: grafana-admin-user
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "grafana.server.fullname" . }}
              key: grafana-admin-password
        args:
          - "http://$(ADMIN_USER):$(ADMIN_PASSWORD)@{{ template "grafana.fullname" . }}:{{ .Values.server.httpPort }}/api/datasources"
          - "--max-time"
          - "10"
          - "-H"
          - "Content-Type: application/json;charset=UTF-8"
          - "--data-binary"
          {{- with .Values.server.setDatasource.datasource }}
          - "{\"name\":\"{{ .name }}\",\"type\":\"{{ .type }}\",\"url\":\"{{ .url }}\",\"database\":\"{{ .database }}\",\"jsonData\":{ {{ .jsonData }} },\"access\":\"{{ .access }}\",\"isDefault\":{{ .isDefault }}}"
          {{- end }}
      restartPolicy: {{ .Values.server.setDatasource.restartPolicy }}
{{- end -}}
