apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: kube-system
  name: system-pv-kube-system
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /Users/Morriz/Documents/Workspace/playground/mostack/minidata/kube-system
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: kube-system
  name: system-pvc-kube-system
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: drone
  name: system-pv-drone
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /Users/Morriz/Documents/Workspace/playground/mostack/minidata/drone
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: drone
  name: system-pvc-drone
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
