apiVersion: v1
kind: PersistentVolume
metadata:
  name: mostack-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /Users/Morriz/Documents/Workspace/playground/mostack/minidata
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mostack-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
