{{- if .Values.selfServiceMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    prometheus: {{ .Values.prometheus }}
  name: {{ template "fullname" . }}
spec:
  jobLabel: {{ template "name" . }}
  selector:
    matchLabels:
      app: {{ template "name" . }}
      prometheus: {{ .Values.prometheus }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
  endpoints:
  - port: http
    interval: 30s
{{- end }}
