apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: coredns
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    prometheus: {{ .Values.global.prometheus }}
  name: {{ template "fullname" . }}
spec:
  jobLabel: {{ template "name" . }}
  selector:
    matchLabels:
      app: {{ .Chart.Name | quote }}
      component: coredns
  namespaceSelector:
    matchNames:
      - "kube-system"
  endpoints:
  - port: http-metrics
    interval: 15s
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
