image:
  registry: docker.io
  org: drone
  name: drone
  tag: 0.8
  pullPolicy: IfNotPresent

service:
  http:
    externalPort: 80
    internalPort: 8000
  grpc:
    externalPort: 9000
    internalPort: 9000
  type: ClusterIP

ingress:
  enabled: false
  # enable TLS via kube-lego
  tls: false
  hostname: drone.example.com
  annotations:
    sidecar.istio.io/inject: 'false'
    kubernetes.io/ingress.class: nginx
#    kubernetes.io/ingress.class: istio
    kubernetes.io/tls-acme: 'true'
    ingress.kubernetes.io/rewrite-target: /

server:
  # Drone server configuration. Values in here get injected as environment variables.
  # See http://readme.drone.io/admin/installation-reference#server-options for a list of possible values.
  env:
    DRONE_DEBUG: "false"
    DRONE_DATABASE_DRIVER: "sqlite3"
    DRONE_DATABASE_DATASOURCE: "drone.sqlite"
    # Drone requires some environment variables to bootstrap the git service or it won't start up.
    # Uncomment this and add your own custom configuration.
    #
    # See http://readme.drone.io/admin/installation-reference/ for more info on these envvars.
    # DRONE_ADMIN: "username1,username2"
    # DRONE_OPEN: "true"
    # DRONE_GITHUB: "true"
    # DRONE_ORGS: "organization1,organization2"
    # DRONE_GITHUB_CLIENT: "github_client_id"
    # DRONE_GITHUB_SECRET: "github_client_secret"
  resources:
    requests:
      memory: 32Mi
      cpu: 40m
    limits:
      memory: 1Gi
      cpu: 1

persistentVolume:
  enabled: false
  accessModes:
    - ReadWriteOnce
  existingClaim:
  size: 20Gi
  ## docker-registry data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass: "-"
  annotations: {}
  subPath: drone

agent:
  # Drone agent configuration. Values in here get injected as environment variables.
  # See http://readme.drone.io/admin/installation-reference#server-options for a list of possible values.
  env:
    DRONE_DEBUG: "false"
  resources:
    requests:
      memory: 32Mi
      cpu: 40m
    limits:
      memory: 1Gi
      cpu: 1

# Uncomment this if you want to set a specific shared secret between
# the agents and servers, otherwise this will be auto-generated.
#shared_secret: supersecret

rbac:
  create: true
  serviceAccountName: default
