apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
data:
  servicemonitor-operator.yaml: |-
      apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      metadata:
        labels:
          app: {{ .Chart.Name | quote }}
          chart: {{ .Chart.Name }}-{{ .Chart.Version }}
          heritage: {{ .Release.Service }}
          release: {{ .Release.Name }}
          prometheus: {{ .Values.prometheus }}
        name: {{ .Values.jobLabel }}
      spec:
        jobLabel: {{ template "name" . }}
        selector:
          matchLabels:
        selector:
          matchLabels:
            operated-prometheus: "true"
        namespaceSelector:
          matchNames:
            - {{ .Release.Namespace | quote }}
        endpoints:
        - port: web
          interval: 30s
