---
# allow nginx + prometheus ingress > api
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-api
  namespace: team-frontend
spec:
  podSelector:
    matchLabels:
      app: api
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: system
    ports:
    - protocol: TCP
      port: 80
  - from:
    - podSelector:
        matchLabels:
          app: prometheus
---
# allow all ingress > prometheus > alertmanager egress
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-prometheus
  namespace: team-frontend
spec:
  podSelector:
    matchLabels:
      app: prometheus
  ingress:
  - ports:
    - protocol: TCP
      port: 9090
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: alertmanager
# @todo: somehow the next block is not working
  - to:
    - podSelector:
        matchLabels:
          app: api
# so using this for now:
#  - to:
#    - ipBlock:
#        cidr: 192.168.0.0/16
---
# allow prometheus ingress > alertmanager
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-alertmanager
  namespace: team-frontend
spec:
  podSelector:
    matchLabels:
      app: alertmanager
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: prometheus
