# Default values for coredns.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: coredns/coredns
  tag: "0.9.10"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

rbac:
  # If true, create & use RBAC resources
  create: true
  # Ignored if rbac.create is true
  serviceAccountName: default

# isClusterService specifies whether chart should be deployed as cluster-service or normal k8s app.
isClusterService: true

# serviceType specifies type of service to be created for this chart.
serviceType: "ClusterIP"

# serviceProtocol specifies the protocol on which to expose the CoreDNS service.
# Can be one of three options: "UDPNTCP" (default), "UDP" or "TCP"
serviceProtocol: "UDPNTCP"

# middleware configuration of CoreDNS refer to https://github.com/coredns/coredns/tree/master/middleware
# for all specific details. set enabled to true/false to enable/disable a middleware.
middleware:
  kubernetes:
    enabled: true
    clusterDomain: "cluster.local"
    clusterIP: "10.96.0.10"
    endpoint: # "https://10.96.0.1:443"
  prometheus:
    enabled: true
    port: "9153"
  errors:
    enabled: true
  log:
    enabled: false
  health:
    enabled: true
  proxy:
    enabled: true
  cache:
    enabled: true
  loadbalance:
    enabled: true
    policy: "round_robin"
  rewrite:
    enabled: false
    entries:
    - from: bla.io
      to: bla.default.svc.cluster.local
  etcd:
    enabled: false
    zones:
      - "k8s.io"
    path: "/skydns"
    endpoint: "http://localhost:2379"
