# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
autoscaler:
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10
annotations:
  sidecar.istio.io/inject: 'false'
  prometheus.io/scrape: 'true'
image:
#  repository:
  tag: latest
  pullPolicy: Always
service:
  name: api
  http:
    externalPort: 80
    internalPort: 3000
  type: ClusterIP
ingress:
  enabled: true
  tls: true
#  hostname:
  annotations:
    kubernetes.io/ingress.class: nginx
#    kubernetes.io/ingress.class: istio
    kubernetes.io/tls-acme: 'true'
    ingress.kubernetes.io/rewrite-target: /
    prometheus.io/scrape: 'true'
resources:
  requests:
    cpu: 100m
  limits:
    memory: 100M
    cpu: 1
