# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: kube-registry.kube-system.svc.cluster.local:31000/krakenfx-api
  tag: latest
  pullPolicy: Always
service:
  name: api
  type: NodePort
  externalPort: 80
  internalPort: 3000
ingress:
  enabled: false
